name: google_map_fade_markers
description: "This package This package integrate for the markers a fade animation when the markers changes"
version: 0.0.1
repository: https://github.com/JoseCaro01/google_map_fade_markers

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_maps_flutter: ^2.5.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6

flutter:


